# Warning!!!!!!
# This is only testing that the plugin works as expected and should not be used in production
name: Testing

on:
  repository_dispatch:
    # and the event_type property from the request body is 'update-tokens'
    types: update-tokens

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test